version: '3.9'

services:
       
      
  postgres:
    image: postgres
    container_name: pdsi-project
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: pdsi-1234
      POSTGRES_DB: pdsi-project-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data 
    

volumes:
    postgres-volume:
        driver: local